spring:
    application:
        name: shop
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shop
        username: karin
        password: kpw
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8080

