CREATE TABLE CATEGORIES (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ITEMS (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    categoryId BIGINT,
    FOREIGN KEY (categoryId) REFERENCES CATEGORIES(id)
);

CREATE TABLE STORES (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE STORE_CATEGORIES (
    id BIGSERIAL PRIMARY KEY,
    storeId BIGINT,
    categoryId BIGINT,
    categoryOrder INT,
    FOREIGN KEY (storeId) REFERENCES STORES(id),
    FOREIGN KEY (categoryId) REFERENCES CATEGORIES(id)
);

CREATE TABLE SHOPPING_LISTS (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE LIST_ITEMS (
    id BIGSERIAL PRIMARY KEY,
    listId BIGINT,
    itemId BIGINT,
    quantity INT,
    PRIMARY KEY (listId, itemId),
    FOREIGN KEY (listId) REFERENCES SHOPPING_LISTS(id),
    FOREIGN KEY (itemId) REFERENCES ITEMS(id)
);